import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/utils/Providers'
import GlobalLayout from '@/components/GlobalLayout'
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

const inter = Inter({ subsets: ['latin'] })

loadDevMessages();
loadErrorMessages();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <GlobalLayout>
            {children}
          </GlobalLayout>
        </Providers>
      </body>
    </html>
  )
}
